name: Deploy Pages

on: [push]

jobs:
  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build website
        run: pnpm build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./build/*
          target: ${{ secrets.DEST_PATH }}
          overwrite: true
          strip_components: 1
